# wrangler.toml
name = "silkeburkhardt"
pages_build_output_dir = "./dist"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "CONTENT_KV"
id = "6e541cb414d64bdd8201e4e022844d66"
preview_id = "ba03ed1850fb4fa48e86c294b39e55b7"

[[r2_buckets]]
binding = "UPLOADS_R2"
bucket_name = "vis-a-vision-uploads"

[vars]
CUSTOMER_ID = "silke"
PREVIEW_LIMIT_PER_DAY = "20"
PUBLISH_LIMIT_PER_DAY = "10"
